In [1]:
import numpy as np

In [2]:
X = np.array([[1,0,1,0],[1,0,1,1,],[0,1,0,1]])
y = np.array([[1],[1],[0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
X.shape

(3, 4)

In [5]:
y

array([[1],
       [1],
       [0]])

In [6]:
y.shape

(3, 1)

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

In [9]:
wh = np.random.uniform(size = (input_neurons, hidden_neurons))
bh = np.random.uniform(size = (1, hidden_neurons))
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
bout = np.random.uniform(size = (1, output_neurons))

In [10]:
wh

array([[0.74628134, 0.90902156, 0.97283712],
       [0.55226639, 0.46041261, 0.60122312],
       [0.85168301, 0.26148853, 0.83978536],
       [0.42712036, 0.63815896, 0.79560965]])

In [11]:
bh

array([[0.33981888, 0.67246521, 0.31211044]])

In [12]:
wout

array([[0.52584262],
       [0.0856741 ],
       [0.621394  ]])

In [13]:
bout

array([[0.89471965]])

In [14]:
a1 = np.dot(X,wh) + bh

In [15]:
a1

array([[1.93778323, 1.8429753 , 2.12473293],
       [2.36490359, 2.48113426, 2.92034258],
       [1.31920564, 1.77103677, 1.70894322]])

In [16]:
z1 = sigmoid(a1)

In [17]:
z1

array([[0.87410841, 0.86330021, 0.89328395],
       [0.91411158, 0.92280863, 0.94884293],
       [0.78904951, 0.85458656, 0.84669916]])

In [18]:
a2 = np.dot(z1,wout) + bout

In [19]:
a2

array([[1.98340687],
       [2.04406459],
       [1.90898524]])

In [20]:
output = sigmoid(a2)

In [21]:
output

array([[0.87904387],
       [0.8853465 ],
       [0.8709051 ]])

In [22]:
y

array([[1],
       [1],
       [0]])

In [23]:
error = y - output

In [24]:
error

array([[ 0.12095613],
       [ 0.1146535 ],
       [-0.8709051 ]])

In [25]:
def derivativeSigmoid(x):
    return x * (1 - x)

In [26]:
slope_output = derivativeSigmoid(output)

In [27]:
slope_output

array([[0.10632575],
       [0.10150807],
       [0.11242941]])

In [28]:
delta_output = error * slope_output

In [29]:
delta_output

array([[ 0.01286075],
       [ 0.01163826],
       [-0.09791534]])

In [30]:
error_hidden = delta_output.dot(wout.T)

In [31]:
error_hidden

array([[ 0.00676273,  0.00110183,  0.00799159],
       [ 0.00611989,  0.0009971 ,  0.00723194],
       [-0.05148806, -0.00838881, -0.06084401]])

In [32]:
slope_hidden = derivativeSigmoid(z1)

In [33]:
delta_hidden = error_hidden * slope_hidden

In [34]:
delta_hidden

array([[ 7.44190539e-04,  1.30030609e-04,  7.61820514e-04],
       [ 4.80482428e-04,  7.10260795e-05,  3.51038644e-04],
       [-8.57020714e-03, -1.04246370e-03, -7.89753317e-03]])

In [35]:
epochs = 10000
alpha = 0.1

In [36]:
wh = np.random.uniform(size = (input_neurons, hidden_neurons))
bh = np.random.uniform(size = (1, hidden_neurons))
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
bout = np.random.uniform(size = (1, output_neurons))

for i in range(epochs):
    #feedforward
    fx = np.dot(X, wh) + bh
    hidden_layer = sigmoid(fx)
    fx1 = np.dot(hidden_layer, wout) + bout
    output = sigmoid(fx1)
    
    #backpropagation
    error_output = y - output
    slope_output = derivativeSigmoid(output)
    delta_output = error_output * slope_output
    
    hidden_error = delta_output.dot(wout.T)
    slope_hidden = derivativeSigmoid(hidden_layer)
    delta_hidden = hidden_error * slope_hidden
    
    wout += hidden_layer.T.dot(delta_output) * alpha
    bout += np.sum(delta_output) * alpha
    wh += X.T.dot(delta_hidden) * alpha
    bh += np.sum(delta_hidden) * alpha

In [37]:
output

array([[0.99045961],
       [0.9813565 ],
       [0.02610424]])

In [38]:
y

array([[1],
       [1],
       [0]])

In [39]:
error_output

array([[ 0.00954039],
       [ 0.0186435 ],
       [-0.02610424]])