In [340]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score

In [341]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [342]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [343]:
dataset.shape

(10000, 14)

In [278]:
pd.unique(dataset['Gender'])

array(['Female', 'Male'], dtype=object)

In [279]:
pd.unique(dataset['Geography'])

array(['France', 'Spain', 'Germany'], dtype=object)

In [280]:
X = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1]

In [281]:
lab = LabelEncoder()
X['Gender'] = lab.fit_transform(X['Gender'])

In [282]:
pd.unique(X['Gender'])

array([0, 1])

In [283]:
X = X.drop('Geography', axis = 1)

In [284]:
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [285]:
geog = dataset['Geography']

In [286]:
geog = lab.fit_transform(geog)

In [287]:
geog

array([0, 2, 0, ..., 0, 1, 0])

In [288]:
np.unique(geog, return_counts = True)

(array([0, 1, 2]), array([5014, 2509, 2477], dtype=int64))

In [289]:
onehot = OneHotEncoder()

In [290]:
geog = onehot.fit_transform(geog.reshape(-1,1))

In [291]:
geog

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [292]:
geog.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [293]:
geog = geog.toarray()

In [294]:
X = np.c_[X, geog]

In [295]:
X[0]

array([6.1900000e+02, 0.0000000e+00, 4.2000000e+01, 2.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       1.0134888e+05, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00])

In [296]:
standard = StandardScaler()
X = standard.fit_transform(X)

In [297]:
new_dataset = np.c_[X,y]

In [298]:
new_dataset

array([[-0.32622142, -1.09598752,  0.29351742, ..., -0.57873591,
        -0.57380915,  1.        ],
       [-0.44003595, -1.09598752,  0.19816383, ..., -0.57873591,
         1.74273971,  0.        ],
       [-1.53679418, -1.09598752,  0.29351742, ..., -0.57873591,
        -0.57380915,  1.        ],
       ...,
       [ 0.60498839, -1.09598752, -0.27860412, ..., -0.57873591,
        -0.57380915,  1.        ],
       [ 1.25683526,  0.91241915,  0.29351742, ...,  1.72790383,
        -0.57380915,  1.        ],
       [ 1.46377078, -1.09598752, -1.04143285, ..., -0.57873591,
        -0.57380915,  0.        ]])

In [299]:
X.shape

(10000, 12)

In [300]:
X.ndim

2

In [301]:
y = np.array(y)

In [302]:
y = y.reshape(-1,1)

In [303]:
y.ndim

2

In [304]:
y.shape

(10000, 1)

In [305]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [306]:
input_neurons = X.shape[1]
hidden_neurons = 3
output_neurons = 1

In [307]:
wh = np.random.uniform(size = (input_neurons, hidden_neurons))
bh = np.random.uniform(size = (1, hidden_neurons))
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
bout = np.random.uniform(size = (1, output_neurons))

In [308]:
wh

array([[0.84848764, 0.27088839, 0.28626257],
       [0.07157961, 0.80197257, 0.8486853 ],
       [0.57099059, 0.85114604, 0.74800999],
       [0.71292834, 0.19715358, 0.94203774],
       [0.35576563, 0.84575527, 0.31814138],
       [0.41378065, 0.9622436 , 0.49656624],
       [0.43328518, 0.11937262, 0.93445687],
       [0.33302066, 0.27610573, 0.52829551],
       [0.73169444, 0.42745798, 0.89317603],
       [0.1046559 , 0.38610265, 0.83481894],
       [0.12532358, 0.61764047, 0.20149862],
       [0.58303169, 0.44290045, 0.27064402]])

In [309]:
bh

array([[0.6355649 , 0.09249535, 0.14183733]])

In [310]:
wout

array([[0.47033212],
       [0.04255126],
       [0.641613  ]])

In [311]:
bout

array([[0.73189978]])

In [312]:
a1 = np.dot(X,wh) + bh

In [313]:
a1

array([[-0.79174262, -2.6165164 , -0.78973331],
       [-0.3782459 , -1.58555313, -3.71094594],
       [ 1.48715213,  2.47865963,  2.47809905],
       ...,
       [-0.8003239 , -3.21275957, -2.29294778],
       [ 1.38700375,  2.20034099,  0.53689999],
       [-0.27004345, -2.38935802, -1.99883601]])

In [314]:
z1 = sigmoid(a1)

In [315]:
z1

array([[0.31179462, 0.06808299, 0.31222594],
       [0.40655003, 0.17001046, 0.02387064],
       [0.81565044, 0.92263217, 0.92259215],
       ...,
       [0.30995624, 0.03868837, 0.09170871],
       [0.80011348, 0.90028013, 0.63109098],
       [0.43289643, 0.08398781, 0.11932519]])

In [316]:
a2 = np.dot(z1,wout) + bout

In [317]:
a2

array([[1.08177204],
       [0.94566319],
       [1.74673266],
       ...,
       [0.9381699 ],
       [1.55144308],
       [1.01563926]])

In [318]:
output = sigmoid(a2)

In [319]:
output

array([[0.74682918],
       [0.72024218],
       [0.85154022],
       ...,
       [0.71872984],
       [0.82512206],
       [0.73412231]])

In [320]:
output.shape

(10000, 1)

In [321]:
y.shape

(10000, 1)

In [322]:
error = y - output

In [323]:
error

array([[ 0.25317082],
       [-0.72024218],
       [ 0.14845978],
       ...,
       [ 0.28127016],
       [ 0.17487794],
       [-0.73412231]])

In [325]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [326]:
def derivativeSigmoid(x):
    return x * (1 - x)

In [327]:
slope_output = derivativeSigmoid(output)

In [328]:
slope_output

array([[0.18907536],
       [0.20149338],
       [0.12641947],
       ...,
       [0.20215726],
       [0.14429565],
       [0.19518674]])

In [329]:
delta_output = error * slope_output

In [330]:
delta_output

array([[ 0.04786836],
       [-0.14512403],
       [ 0.01876821],
       ...,
       [ 0.0568608 ],
       [ 0.02523413],
       [-0.14329094]])

In [331]:
error_hidden = delta_output.dot(wout.T)

In [332]:
error_hidden

array([[ 0.02251403,  0.00203686,  0.03071296],
       [-0.06825649, -0.00617521, -0.09311347],
       [ 0.00882729,  0.00079861,  0.01204193],
       ...,
       [ 0.02674346,  0.0024195 ,  0.03648263],
       [ 0.01186842,  0.00107374,  0.01619054],
       [-0.06739433, -0.00609721, -0.09193733]])

In [333]:
slope_hidden = derivativeSigmoid(z1)

In [334]:
delta_hidden = error_hidden * slope_hidden

In [335]:
epochs = 10000
alpha = 0.1

In [336]:
wh = np.random.uniform(size = (input_neurons, hidden_neurons))
bh = np.random.uniform(size = (1, hidden_neurons))
wout = np.random.uniform(size = (hidden_neurons, output_neurons))
bout = np.random.uniform(size = (1, output_neurons))

for i in range(epochs):
    #feedforward
    fx = np.dot(X, wh) + bh
    hidden_layer = sigmoid(fx)
    fx1 = np.dot(hidden_layer, wout) + bout
    output = sigmoid(fx1)
    
    #backpropagation
    error_output = y - output
    slope_output = derivativeSigmoid(output)
    delta_output = error_output * slope_output
    
    hidden_error = delta_output.dot(wout.T)
    slope_hidden = derivativeSigmoid(hidden_layer)
    delta_hidden = hidden_error * slope_hidden
    
    wout += hidden_layer.T.dot(delta_output) * alpha
    bout += np.sum(delta_output) * alpha
    wh += X.T.dot(delta_hidden) * alpha
    bh += np.sum(delta_hidden) * alpha

In [337]:
output

array([[7.49012981e-43],
       [7.49012979e-43],
       [7.49012553e-43],
       ...,
       [7.49012981e-43],
       [7.48982701e-43],
       [7.49012980e-43]])

In [338]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [339]:
error_output

array([[ 1.00000000e+00],
       [-7.49012979e-43],
       [ 1.00000000e+00],
       ...,
       [ 1.00000000e+00],
       [ 1.00000000e+00],
       [-7.49012980e-43]])

In [344]:
accuracy_score(output,y)

ValueError: Classification metrics can't handle a mix of continuous and binary targets